"use client";

import { Funnel, X } from "@phosphor-icons/react";
import { useState } from "react";

type Props = { zona: string; modalidad: string; minPay: number; maxPay: number; day: string; start: string; end: string };
const days = [["lun", "Lun"], ["mar", "Mar"], ["mie", "Mié"], ["jue", "Jue"], ["vie", "Vie"], ["sab", "Sáb"], ["dom", "Dom"]];

function Fields({ values }: { values: Props }) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><label className="flex flex-col gap-1 text-body-sm text-ink-600">Zona<input name="zona" defaultValue={values.zona} className="min-h-11 rounded-sm border border-border-strong bg-bg px-3" /></label><label className="flex flex-col gap-1 text-body-sm text-ink-600">Modalidad<select name="modalidad" defaultValue={values.modalidad} className="min-h-11 rounded-sm border border-border-strong bg-bg px-3"><option value="">Todas</option><option value="planta">De planta</option><option value="entrada_salida">Entrada por salida</option><option value="ocasional">Ocasional</option></select></label><fieldset className="sm:col-span-2 xl:col-span-1"><legend className="text-body-sm text-ink-600">Rango de pago (MXN)</legend><div className="mt-1 grid grid-cols-2 gap-2"><input aria-label="Pago mínimo" name="pago_min" type="number" min="0" defaultValue={values.minPay || ""} placeholder="Mínimo" className="min-h-11 min-w-0 rounded-sm border border-border-strong bg-bg px-3" /><input aria-label="Pago máximo" name="pago_max" type="number" min="0" defaultValue={values.maxPay || ""} placeholder="Máximo" className="min-h-11 min-w-0 rounded-sm border border-border-strong bg-bg px-3" /></div></fieldset><fieldset className="sm:col-span-2 xl:col-span-1"><legend className="text-body-sm text-ink-600">Disponibilidad</legend><div className="mt-1 grid grid-cols-2 gap-2"><select name="dia" aria-label="Día" defaultValue={values.day} className="min-h-11 rounded-sm border border-border-strong bg-bg px-3"><option value="">Cualquier día</option>{days.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="hora_desde" aria-label="Desde" type="time" defaultValue={values.start} className="min-h-11 rounded-sm border border-border-strong bg-bg px-3" /><input name="hora_hasta" aria-label="Hasta" type="time" defaultValue={values.end} className="min-h-11 rounded-sm border border-border-strong bg-bg px-3" /></div></fieldset></div>;
}

export function OpportunityFilters(props: Props) {
  const [open, setOpen] = useState(false);
  return <><div className="mb-5 flex items-center justify-between lg:hidden"><button type="button" onClick={() => setOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-sm border border-border-strong px-4 text-button"><Funnel size={18} aria-hidden="true" />Filtrar vacantes</button></div><aside aria-label="Filtros de vacantes" className="hidden w-64 shrink-0 rounded-md border border-border bg-bg-raised p-4 lg:block"><h2 className="text-h2">Filtros</h2><form method="get" className="mt-5"><Fields values={props} /><button type="submit" className="mt-5 min-h-11 rounded-sm bg-primary-600 px-4 text-button text-white">Aplicar filtros</button></form></aside>{open && <div className="fixed inset-0 z-50 bg-black/40 lg:hidden" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="opportunity-filters-title" className="absolute inset-x-0 bottom-0 max-h-[90vh] overflow-y-auto rounded-t-lg bg-bg-raised p-5"><div className="flex items-center justify-between"><h2 id="opportunity-filters-title" className="text-h2">Filtros</h2><button type="button" aria-label="Cerrar filtros" onClick={() => setOpen(false)} className="flex h-11 w-11 items-center justify-center"><X size={20} aria-hidden="true" /></button></div><form method="get" className="mt-5" onSubmit={() => setOpen(false)}><Fields values={props} /><div className="mt-6 flex items-center justify-between border-t border-border pt-4"><button type="button" onClick={() => setOpen(false)} className="min-h-11 text-button text-primary-700">Cancelar</button><button type="submit" className="min-h-11 rounded-sm bg-primary-600 px-4 text-button text-white">Aplicar filtros</button></div></form></section></div>}</>;
}
