"use client";
/* eslint-disable @next/next/no-img-element -- profile photos are remote Supabase URLs. */

import { useRef, useState, useTransition } from "react";
import Link from "next/link";
import { Camera, ChatCircleText } from "@phosphor-icons/react/ssr";
import { TrustBadge, type VerificationStatus } from "@/components/shared/trust-badge";
import { savePerfilNineraSectionAction, uploadPerfilFotoAction, type PerfilNineraSection } from "@/actions/perfil-ninera";
import { ZonaMultiSelect } from "@/components/ninera/zona-multi-select";
import { rangoEdadValues, diasValues } from "@/lib/familia/necesidad-validation";
import { modalidadValues } from "@/lib/ninera/perfil-validation";
import type { ZonaOption } from "@/lib/zonas/queries";

type Schedule = { dia: typeof diasValues[number]; horaInicio: string; horaFin: string };
type Reference = { nombre: string; relacion: string; periodo: string; contacto?: string | null };
type Profile = { nombre: string; fotoUrl: string; verificationStatus: VerificationStatus; zonaIds: string[]; anosExperiencia: number; disponibilidad: Schedule[]; salarioMin: number; salarioMax: number; modalidadesAceptadas: typeof modalidadValues[number][]; experienciaEdades: typeof rangoEdadValues[number][]; descripcion: string; referencias: Reference[] };
const dayLabels: Record<string, string> = { lun: "Lun", mar: "Mar", mie: "Mié", jue: "Jue", vie: "Vie", sab: "Sáb", dom: "Dom" };
const modalityLabels: Record<string, string> = { planta: "Planta", entrada_salida: "Entrada por salida", ocasional: "Ocasional" };
const inputClass = "h-11 rounded-sm border border-border-strong bg-bg-raised px-3 disabled:opacity-70";

export function PerfilNineraEdit({ initial, zonas }: { initial: Profile; zonas: ZonaOption[] }) {
  const [data, setData] = useState(initial);
  const [savedData, setSavedData] = useState(initial);
  const [editing, setEditing] = useState<Partial<Record<PerfilNineraSection, boolean>>>({});
  const [feedback, setFeedback] = useState<Partial<Record<PerfilNineraSection, string>>>({});
  const [rowEditing, setRowEditing] = useState<Set<number>>(new Set());
  const [pending, startTransition] = useTransition();
  const [photoFeedback, setPhotoFeedback] = useState("");
  const photoInput = useRef<HTMLInputElement>(null);
  const set = <K extends keyof Profile>(key: K, value: Profile[K]) => setData((current) => ({ ...current, [key]: value }));
  const save = (section: PerfilNineraSection, payload: unknown) => startTransition(async () => {
    setFeedback((current) => ({ ...current, [section]: "Guardando…" }));
    const result = await savePerfilNineraSectionAction({ status: "idle" }, section, payload);
    if (result.status === "error") { setFeedback((current) => ({ ...current, [section]: result.message ?? "No se pudo guardar." })); return; }
    const identityChanged = section === "identity" && data.verificationStatus === "verificada" && (data.nombre !== savedData.nombre || data.fotoUrl !== savedData.fotoUrl);
    if (identityChanged) setData((current) => ({ ...current, verificationStatus: "en_proceso" }));
    setSavedData((current) => section === "references" ? { ...current, referencias: data.referencias } : section === "identity" ? { ...current, nombre: data.nombre, fotoUrl: data.fotoUrl, verificationStatus: identityChanged ? "en_proceso" : current.verificationStatus } : current);
    setFeedback((current) => ({ ...current, [section]: "✓ Guardado" }));
    setEditing((current) => ({ ...current, [section]: false }));
    if (section === "references") setRowEditing(new Set());
  });
  const restore = (section: PerfilNineraSection) => { if (section === "references") setData((d) => ({ ...d, referencias: savedData.referencias })); else if (section === "identity") setData((d) => ({ ...d, nombre: savedData.nombre, fotoUrl: savedData.fotoUrl })); setEditing((current) => ({ ...current, [section]: false })); setRowEditing(new Set()); setFeedback((current) => ({ ...current, [section]: "Edición cancelada; se restauraron tus cambios guardados." })); };
  const controls = (section: PerfilNineraSection, payload: unknown) => editing[section] ? <div className="flex flex-wrap gap-3"><button type="button" disabled={pending} onClick={() => save(section, payload)} className="min-h-11 rounded-sm bg-primary-600 px-4 text-button text-white">{pending ? "Guardando…" : "Guardar sección"}</button><button type="button" disabled={pending} onClick={() => restore(section)} className="min-h-11 px-3 text-button text-ink-600">Cancelar</button></div> : <button type="button" onClick={() => setEditing((current) => ({ ...current, [section]: true }))} className="min-h-11 px-3 text-button text-primary-700 underline">Editar</button>;
  const updateReference = (index: number, patch: Partial<Reference>) => set("referencias", data.referencias.map((reference, i) => i === index ? { ...reference, ...patch } : reference));
  return <main className="mx-auto min-h-screen w-full max-w-3xl bg-bg px-5 py-8 pb-24 text-ink-900 sm:px-8 lg:py-12">
    <header className="mb-8"><nav aria-label="Navegación de niñera" className="flex gap-2 border-b border-border pb-3"><Link href="/ninera" className="inline-flex min-h-11 items-center px-3 text-body-sm text-primary-700">Inicio</Link><span className="inline-flex min-h-11 items-center border-b-2 border-primary-600 px-3 text-body-sm font-semibold">Mi perfil</span><Link href="/ninera/perfil/identificacion" className="inline-flex min-h-11 items-center px-3 text-body-sm text-primary-700">Identificación</Link></nav><h1 className="mt-5 text-h1">Mi perfil</h1><div className="mt-4 flex flex-wrap items-center gap-3"><TrustBadge status={data.verificationStatus} size="detail" />{data.verificationStatus !== "verificada" && <Link href="/ninera/perfil/identificacion" className="inline-flex min-h-11 items-center px-2 text-button text-primary-700 underline">{data.verificationStatus === "en_proceso" ? "Ver estado" : "Subir identificación"}</Link>}</div></header>
    <div className="space-y-6">
      <Section title="Identidad" feedback={feedback.identity || photoFeedback}><div className="flex items-center gap-4">{data.fotoUrl ? <img src={data.fotoUrl} alt="Tu foto de perfil" className="h-20 w-20 rounded-full object-cover" /> : <div className="flex h-20 w-20 items-center justify-center rounded-full border border-border bg-bg-raised text-body-sm text-ink-600">Sin foto</div>}{editing.identity && <><button type="button" disabled={pending} onClick={() => photoInput.current?.click()} className="inline-flex min-h-11 items-center gap-2 rounded-sm border border-border-strong px-4 text-button"><Camera size={18} aria-hidden />Cambiar foto</button><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const form = new FormData(); form.set("foto", file); setPhotoFeedback("Subiendo foto…"); startTransition(async () => { const result = await uploadPerfilFotoAction({ status: "idle" }, form); if (result.status === "uploaded" && result.fotoUrl) { set("fotoUrl", result.fotoUrl); setPhotoFeedback("Foto subida. Guarda la sección para aplicar el cambio."); } else setPhotoFeedback(result.message ?? "No se pudo subir la foto."); }); }} /></>}</div>{editing.identity && <label className="flex flex-col gap-2 text-body-sm">Nombre<input className={inputClass} value={data.nombre} onChange={(e) => set("nombre", e.target.value)} /></label>}{!editing.identity && <p className="text-body">{data.nombre}</p>}{controls("identity", { nombre: data.nombre, fotoUrl: data.fotoUrl })}</Section>
      <Section title="Experiencia y zonas" feedback={feedback.work}>{editing.work ? <><label className="flex flex-col gap-2 text-body-sm">Años de experiencia<input type="number" min="0" className={inputClass} value={data.anosExperiencia} onChange={(e) => set("anosExperiencia", Number(e.target.value))} /></label><ZonaMultiSelect zonas={zonas} name="zona_ids" defaultZonaIds={data.zonaIds} onChange={(ids) => set("zonaIds", ids)} /><fieldset><legend className="mb-2 text-body-sm">Experiencia con edades</legend><div className="flex flex-wrap gap-2">{rangoEdadValues.map((age) => <button key={age} type="button" aria-pressed={data.experienciaEdades.includes(age)} onClick={() => set("experienciaEdades", data.experienciaEdades.includes(age) ? data.experienciaEdades.filter((x) => x !== age) : [...data.experienciaEdades, age])} className={`min-h-11 rounded-full border px-4 ${data.experienciaEdades.includes(age) ? "border-primary-600 bg-primary-50" : "border-border-strong"}`}>{age}</button>)}</div></fieldset>{controls("work", { zonaIds: data.zonaIds, anosExperiencia: data.anosExperiencia, experienciaEdades: data.experienciaEdades })}</> : <><p className="text-body">{data.anosExperiencia} años de experiencia</p><p className="text-body-sm text-ink-600">{data.experienciaEdades.join(" · ") || "Sin edades indicadas"}</p>{controls("work", {})}</>}</Section>
      <Section title="Disponibilidad y modalidad" feedback={feedback.availability}>{editing.availability ? <><fieldset><legend className="mb-2 text-body-sm">Disponibilidad</legend><div className="space-y-3">{diasValues.map((day) => { const item = data.disponibilidad.find((x) => x.dia === day); return <div key={day} className="flex flex-wrap items-center gap-2"><button type="button" aria-pressed={!!item} onClick={() => set("disponibilidad", item ? data.disponibilidad.filter((x) => x.dia !== day) : [...data.disponibilidad, { dia: day, horaInicio: "09:00", horaFin: "17:00" }])} className={`min-h-11 min-w-16 rounded-full border px-3 ${item ? "border-primary-600 bg-primary-50" : "border-border-strong"}`}>{dayLabels[day]}</button>{item && <><input aria-label={`${day} desde`} type="time" className={inputClass} value={item.horaInicio} onChange={(e) => set("disponibilidad", data.disponibilidad.map((x) => x.dia === day ? { ...x, horaInicio: e.target.value } : x))} /><span>—</span><input aria-label={`${day} hasta`} type="time" className={inputClass} value={item.horaFin} onChange={(e) => set("disponibilidad", data.disponibilidad.map((x) => x.dia === day ? { ...x, horaFin: e.target.value } : x))} /></>}</div>; })}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2 text-body-sm">Mínimo semanal<input type="number" min="0" className={inputClass} value={data.salarioMin} onChange={(e) => set("salarioMin", Number(e.target.value))} /></label><label className="flex flex-col gap-2 text-body-sm">Máximo semanal<input type="number" min="0" className={inputClass} value={data.salarioMax} onChange={(e) => set("salarioMax", Number(e.target.value))} /></label></div><fieldset><legend className="mb-2 text-body-sm">Modalidades aceptadas</legend><div className="flex flex-wrap gap-2">{modalidadValues.map((mode) => <button key={mode} type="button" aria-pressed={data.modalidadesAceptadas.includes(mode)} onClick={() => set("modalidadesAceptadas", data.modalidadesAceptadas.includes(mode) ? data.modalidadesAceptadas.filter((x) => x !== mode) : [...data.modalidadesAceptadas, mode])} className={`min-h-11 rounded-full border px-4 ${data.modalidadesAceptadas.includes(mode) ? "border-primary-600 bg-primary-50" : "border-border-strong"}`}>{modalityLabels[mode]}</button>)}</div></fieldset>{controls("availability", { disponibilidad: data.disponibilidad, salarioMin: data.salarioMin, salarioMax: data.salarioMax, modalidadesAceptadas: data.modalidadesAceptadas })}</> : <><p className="text-body">{data.disponibilidad.map((x) => `${dayLabels[x.dia]} ${x.horaInicio}–${x.horaFin}`).join(" · ") || "Sin disponibilidad indicada"}</p>{controls("availability", {})}</>}</Section>
      <Section title="Descripción personal" feedback={feedback.about}>{editing.about ? <><textarea maxLength={1000} rows={5} className="rounded-sm border border-border-strong bg-bg-raised p-3" value={data.descripcion} onChange={(e) => set("descripcion", e.target.value)} />{controls("about", { descripcion: data.descripcion })}</> : <><p className="whitespace-pre-wrap text-body">{data.descripcion || "Aún no has agregado una descripción."}</p>{controls("about", {})}</>}</Section>
      <ReferenceEditor editing={!!editing.references} pending={pending} references={data.referencias} feedback={feedback.references} rowEditing={rowEditing} setRowEditing={setRowEditing} updateReference={updateReference} addReference={() => { set("referencias", [...data.referencias, { nombre: "", relacion: "", periodo: "", contacto: null }]); setRowEditing(new Set([...rowEditing, data.referencias.length])); }} removeReference={(i) => set("referencias", data.referencias.filter((_, n) => n !== i))} onEdit={() => setEditing((current) => ({ ...current, references: true }))} onSave={() => save("references", { referencias: data.referencias })} onCancel={() => restore("references")} />
    </div>
  </main>;
}

function ReferenceEditor({ editing, pending, references, feedback, rowEditing, setRowEditing, updateReference, addReference, removeReference: removeReferenceAction, onEdit, onSave, onCancel }: { editing: boolean; pending: boolean; references: Reference[]; feedback?: string; rowEditing: Set<number>; setRowEditing: (value: Set<number>) => void; updateReference: (index: number, patch: Partial<Reference>) => void; addReference: () => void; removeReference: (index: number) => void; onEdit: () => void; onSave: () => void; onCancel: () => void }) {
  const toggleRow = (index: number) => setRowEditing(new Set(rowEditing).add(index));
  const removeReference = (index: number) => { removeReferenceAction(index); setRowEditing(new Set()); };
  return <section aria-labelledby="references-heading" className="mt-3 border-t border-border pt-6"><h2 id="references-heading" className="flex flex-wrap items-center justify-between gap-3 text-h2"><span className="flex items-center gap-2"><ChatCircleText size={18} className="text-ink-400" aria-hidden="true" />Referencias</span>{feedback && <span className="text-body-sm text-ink-600" role="status" aria-live="polite">{feedback}</span>}</h2><p className="mt-2 text-body-sm text-ink-600">Proporcionadas por la niñera — Clin no las ha verificado.</p>{references.length > 0 && <ul className="mt-4 divide-y divide-border border-y border-border">{references.map((reference, index) => { const rowIsEditing = editing && rowEditing.has(index); return <li key={index} className="py-4 text-body"><div className="flex flex-wrap items-start justify-between gap-3">{rowIsEditing ? <div className="grid w-full gap-3 sm:grid-cols-2"><Field label="Nombre" value={reference.nombre} onChange={(value) => updateReference(index, { nombre: value })} /><Field label="Relación" value={reference.relacion} onChange={(value) => updateReference(index, { relacion: value })} /><Field label="Periodo" value={reference.periodo} onChange={(value) => updateReference(index, { periodo: value })} /><Field label="Contacto (opcional)" value={reference.contacto ?? ""} onChange={(value) => updateReference(index, { contacto: value || null })} /></div> : <div><p>{reference.nombre}</p><p className="text-body-sm text-ink-600">{reference.relacion}, {reference.periodo}</p>{reference.contacto && <p className="mt-1 text-body-sm text-ink-600">Contacto: {reference.contacto}</p>}</div>}{editing && <div className="flex flex-wrap gap-2"><button type="button" disabled={pending} onClick={() => rowIsEditing ? setRowEditing(new Set([...rowEditing].filter((row) => row !== index))) : toggleRow(index)} className="min-h-11 px-3 text-button text-primary-700 underline">{rowIsEditing ? "Guardar fila" : "Editar"}</button><button type="button" disabled={pending} onClick={() => removeReference(index)} className="min-h-11 px-3 text-button text-danger-600 underline">Quitar</button></div>}</div></li>; })}</ul>}{editing ? <><button type="button" onClick={addReference} className="mt-4 min-h-11 text-button text-primary-700 underline">Agregar referencia</button><div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={pending} onClick={onSave} className="min-h-11 rounded-sm bg-primary-600 px-4 text-button text-white">{pending ? "Guardando…" : "Guardar sección"}</button><button type="button" disabled={pending} onClick={onCancel} className="min-h-11 px-3 text-button text-ink-600">Cancelar</button></div></> : <button type="button" onClick={onEdit} className="mt-4 min-h-11 px-3 text-button text-primary-700 underline">Editar</button>}</section>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex flex-col gap-2 text-body-sm">{label}<input className={inputClass} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Section({ title, feedback, children }: { title: string; feedback?: string; children: React.ReactNode }) { return <section className="space-y-4 rounded-md border border-border bg-bg-raised p-5"><h2 className="flex flex-wrap items-center justify-between gap-3 text-h2"><span>{title}</span>{feedback && <span className="text-body-sm text-ink-600" role="status" aria-live="polite">{feedback}</span>}</h2>{children}</section>; }
