"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { SpinnerGap } from "@phosphor-icons/react/ssr";
import { ZonaAutocomplete } from "@/components/familia/zona-autocomplete";
import { saveNecesidadDraftAction } from "@/actions/necesidad";
import { rangoEdadValues, type NecesidadDraft } from "@/lib/familia/necesidad-validation";
import type { ZonaOption } from "@/lib/zonas/queries";

const labels = ["Niños", "Zona", "Días y horarios", "Modalidad", "Rango de pago", "Fecha de inicio", "Responsabilidades"];
const responsibilityOptions = ["Preparar alimentos", "Ayuda con tareas", "Transporte escolar", "Jugar y acompañar", "Baño y rutina", "Orden del espacio", "Cuidado de mascotas"];
type WizardData = NecesidadDraft & { children: NonNullable<NecesidadDraft["children"]>; diasHorarios: NonNullable<NecesidadDraft["diasHorarios"]>; responsabilidades: NonNullable<NecesidadDraft["responsabilidades"]>; zonaId: string };

export function NecesidadWizard({ zonas, draft, initialDraftId }: { zonas: ZonaOption[]; draft?: Partial<NecesidadDraft>; initialDraftId?: string }) {
  const [data, setData] = useState<WizardData>({ children: draft?.children ?? [], zonaId: draft?.zonaId ?? "", diasHorarios: draft?.diasHorarios ?? [], modalidad: draft?.modalidad, pagoMin: draft?.pagoMin, pagoMax: draft?.pagoMax, fechaInicio: draft?.fechaInicio, responsabilidades: draft?.responsabilidades ?? [] });
  const [draftId, setDraftId] = useState(initialDraftId); const [step, setStep] = useState(1); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [isPending, startTransition] = useTransition(); const router = useRouter();
  const [isDesktop, setIsDesktop] = useState(false);
  useEffect(() => { if (!window.matchMedia) return; const query = window.matchMedia("(min-width: 1024px)"); const updateDesktop = () => setIsDesktop(query.matches); updateDesktop(); query.addEventListener("change", updateDesktop); return () => query.removeEventListener("change", updateDesktop); }, []);
  const update = (patch: Partial<WizardData>) => setData((current) => ({ ...current, ...patch }));
  const persist = (validationStep: number) => { const fd = new FormData(); fd.set("draft", JSON.stringify(data)); fd.set("step", String(validationStep)); if (draftId) fd.set("draft_id", draftId); return saveNecesidadDraftAction({ status: "idle" }, fd); };
  const afterSave = (result: Awaited<ReturnType<typeof saveNecesidadDraftAction>>) => { if (result.status === "error") { setError(result.message ?? "No se pudo guardar el borrador."); return false; } setDraftId(result.draftId); setNotice("Guardado"); setTimeout(() => setNotice(""), 1800); return true; };
  const next = () => { setError(""); startTransition(async () => { const ok = afterSave(await persist(step)); if (ok && step < 7) setStep(step + 1); }); };
  const back = () => { setError(""); startTransition(async () => { const ok = afterSave(await persist(1)); if (ok) setStep((current) => current - 1); }); };
  const exit = () => { setError(""); startTransition(async () => { if (afterSave(await persist(1))) router.push("/familia"); }); };
  const canNext = step === 1 ? data.children.length > 0 && data.children.every(Boolean) : step === 2 ? !!data.zonaId : step === 3 ? data.diasHorarios.length > 0 : step === 4 ? !!data.modalidad : step === 5 ? data.pagoMin !== undefined && data.pagoMax !== undefined : step === 6 ? !!data.fechaInicio : data.responsabilidades.length > 0;
  const other = data.responsabilidades.find((item) => !responsibilityOptions.includes(item)) ?? "";
  const paymentSummary = data.pagoMin !== undefined || data.pagoMax !== undefined ? `$${data.pagoMin?.toLocaleString("es-MX") ?? "—"} – $${data.pagoMax?.toLocaleString("es-MX") ?? "—"} MXN/semana` : "Ejemplo: $4,500 – $6,500 MXN/semana";
  const selectDesktopSection = (section: number) => { setStep(section); const target = document.getElementById(`step-${section}`); target?.scrollIntoView?.({ behavior: "smooth", block: "start" }); target?.focus(); };
  return <main className="mx-auto flex min-h-screen w-full max-w-[1040px] flex-col bg-bg px-4 py-6 text-ink-900 sm:px-6 lg:flex-row lg:gap-10 lg:py-12">
     <aside className="hidden w-[200px] shrink-0 lg:block"><nav aria-label="Pasos de la necesidad" className="sticky top-12 space-y-1">{labels.map((label, i) => <button key={label} type="button" aria-current={i + 1 === step ? "step" : undefined} disabled={isPending} onClick={() => selectDesktopSection(i + 1)} className={`min-h-11 w-full rounded-sm px-3 text-left text-body-sm ${i + 1 === step ? "bg-primary-50 font-semibold text-primary-700" : "text-ink-600"}`}>{i + 1}. {label}</button>)}</nav></aside>
    <div className="w-full max-w-[640px]"><div className="mb-8 flex gap-1 lg:hidden" aria-label={`Paso ${step} de 7`}>{labels.map((label, i) => <span key={label} title={label} className={`h-1 flex-1 rounded-full ${i < step ? "bg-primary-600" : "bg-border"}`} />)}</div><div className="mb-6 flex items-center justify-between"><p className="text-body-sm text-ink-600">Paso {step} de 7 · {labels[step - 1]}</p>{notice && <span className="text-body-sm text-ink-600">{notice}</span>}</div>
       {isDesktop ? <><DesktopSections data={data} zonas={zonas} paymentSummary={paymentSummary} update={update} onSectionVisible={setStep} /><DesktopActions canNext={canNext} error={error} isPending={isPending} step={step} back={back} next={next} exit={exit} /></> : <>
      <section className="min-h-[420px]"><h1 className="mb-2 text-h1">{labels[step - 1]}</h1><p className="mb-8 text-body text-ink-600">Cuéntanos lo necesario para encontrar una opción compatible.</p>
        {step === 1 && <div className="space-y-6"><p>¿Cuántos niños cuidarás?</p><div className="flex items-center gap-5"><button type="button" aria-label="Quitar niño" className="min-h-11 min-w-11 rounded-sm border border-border-strong text-xl" onClick={() => update({ children: data.children.slice(0, -1) })}>−</button><span>{data.children.length}</span><button type="button" aria-label="Agregar niño" className="min-h-11 min-w-11 rounded-sm border border-border-strong text-xl" onClick={() => update({ children: [...data.children, ""] as WizardData["children"] })}>+</button></div>{data.children.map((age, i) => <fieldset key={i}><legend className="mb-2 text-body-sm">Edad del niño {i + 1}</legend><div className="flex flex-wrap gap-2">{rangoEdadValues.map((value) => <button key={value} type="button" aria-pressed={age === value} className={`min-h-11 rounded-full border px-4 py-2 text-body-sm ${age === value ? "border-primary-600 bg-primary-50" : "border-border-strong"}`} onClick={() => update({ children: data.children.map((item, index) => index === i ? value : item) as WizardData["children"] })}>{value}</button>)}</div></fieldset>)}</div>}
        {step === 2 && <ZonaAutocomplete zonas={zonas} name="zona_id" defaultZonaId={data.zonaId} onSelect={(zona) => update({ zonaId: zona.id })} />}
        {step === 3 && <div className="flex flex-wrap gap-3">{["lun", "mar", "mie", "jue", "vie", "sab", "dom"].map((day) => { const current = data.diasHorarios.find((item) => item.dia === day); return <div key={day} className="flex flex-col gap-2"><button type="button" aria-pressed={!!current} className={`min-h-11 rounded-full border px-4 ${current ? "border-primary-600 bg-primary-50" : "border-border-strong"}`} onClick={() => update({ diasHorarios: current ? data.diasHorarios.filter((item) => item.dia !== day) : [...data.diasHorarios, { dia: day as "lun", horaInicio: "09:00", horaFin: "17:00" }] })}>{day}</button>{current && <div className="flex gap-2"><label className="text-body-sm">Desde<input className="mt-1 h-11 rounded-sm border border-border-strong bg-bg-raised px-2" type="time" aria-label={`${day} desde`} value={current.horaInicio} onChange={(e) => update({ diasHorarios: data.diasHorarios.map((item) => item.dia === day ? { ...item, horaInicio: e.target.value } : item) })} /></label><label className="text-body-sm">Hasta<input className="mt-1 h-11 rounded-sm border border-border-strong bg-bg-raised px-2" type="time" aria-label={`${day} hasta`} value={current.horaFin} onChange={(e) => update({ diasHorarios: data.diasHorarios.map((item) => item.dia === day ? { ...item, horaFin: e.target.value } : item) })} /></label></div>}</div>; })}</div>}
        {step === 4 && <div className="grid gap-3">{[["planta", "Planta"], ["entrada_salida", "Entrada por salida"], ["ocasional", "Ocasional"]].map(([value, label]) => <button key={value} type="button" aria-pressed={data.modalidad === value} className="min-h-11 rounded-sm border border-border-strong p-4 text-left" onClick={() => update({ modalidad: value as WizardData["modalidad"] })}>{label}</button>)}</div>}
      {step === 5 && <div className="grid gap-5 sm:grid-cols-2"><label className="flex flex-col gap-2 text-body-sm">Pago mínimo (MXN)<span className="flex h-11 items-center rounded-sm border border-border-strong bg-bg-raised"><span className="px-3 text-ink-600">MXN</span><input aria-label="Pago mínimo en MXN" type="number" min="0" className="h-full min-w-0 flex-1 bg-transparent px-2 outline-none" value={data.pagoMin ?? ""} onChange={(e) => update({ pagoMin: e.target.value ? Number(e.target.value) : undefined })} /></span></label><label className="flex flex-col gap-2 text-body-sm">Pago máximo (MXN)<span className="flex h-11 items-center rounded-sm border border-border-strong bg-bg-raised"><span className="px-3 text-ink-600">MXN</span><input aria-label="Pago máximo en MXN" type="number" min="0" className="h-full min-w-0 flex-1 bg-transparent px-2 outline-none" value={data.pagoMax ?? ""} onChange={(e) => update({ pagoMax: e.target.value ? Number(e.target.value) : undefined })} /></span></label><p className="text-body-sm text-ink-600 sm:col-span-2" aria-live="polite">{paymentSummary}</p></div>}
        {step === 6 && <label className="flex max-w-xs flex-col gap-2 text-body-sm">Fecha de inicio<input type="date" min={new Date().toISOString().slice(0, 10)} className="h-11 rounded-sm border border-border-strong bg-bg-raised px-3" value={data.fechaInicio ?? ""} onChange={(e) => update({ fechaInicio: e.target.value })} /></label>}
        {step === 7 && <div className="space-y-3">{responsibilityOptions.map((item) => <label key={item} className="flex min-h-11 items-center gap-3 text-body"><input type="checkbox" checked={data.responsabilidades.includes(item)} onChange={(e) => update({ responsabilidades: e.target.checked ? [...data.responsabilidades, item] : data.responsabilidades.filter((x) => x !== item) })} />{item}</label>)}<label className="flex flex-col gap-2 text-body-sm">Otros<textarea value={other} className="rounded-sm border border-border-strong bg-bg-raised p-3" onChange={(e) => update({ responsabilidades: e.target.value ? [...data.responsabilidades.filter((x) => responsibilityOptions.includes(x)), e.target.value] : data.responsabilidades.filter((x) => responsibilityOptions.includes(x)) })} /></label></div>}
        {error && <p role="alert" className="mt-5 text-body-sm text-danger-600">{error}</p>}
      </section><div className="sticky bottom-0 z-10 -mx-4 mt-8 flex flex-wrap gap-3 border-t border-border bg-bg/95 px-4 py-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:-mx-6 sm:px-6 lg:static lg:mx-0 lg:bg-transparent lg:px-0"><button type="button" disabled={isPending || step === 1} onClick={back} className="min-h-11 rounded-sm px-4 py-3 text-button text-ink-600 disabled:opacity-40">Atrás</button><button type="button" disabled={isPending} onClick={exit} className="min-h-11 rounded-sm px-4 py-3 text-button text-ink-600 disabled:opacity-40">Guardar y salir</button><button type="button" disabled={!canNext || isPending} onClick={next} className="flex min-h-11 flex-1 items-center justify-center rounded-sm bg-primary-600 px-4 py-3 text-button text-white disabled:opacity-40">{isPending ? <SpinnerGap size={16} className="animate-spin" aria-label="Guardando" /> : step === 7 ? "Guardar borrador" : "Siguiente"}</button></div>
     </> }</div></main>;
}

function DesktopSections({ data, zonas, paymentSummary, update, onSectionVisible }: { data: WizardData; zonas: ZonaOption[]; paymentSummary: string; update: (patch: Partial<WizardData>) => void; onSectionVisible: (section: number) => void }) {
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!containerRef.current || typeof IntersectionObserver === "undefined") return;
    const container = containerRef.current;
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
      if (visible) onSectionVisible(Number((visible.target as HTMLElement).id.replace("step-", "")));
    }, { root: container, threshold: [0.25, 0.5, 0.75] });
    container.querySelectorAll("section[id^='step-']").forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, [onSectionVisible]);

  return <div ref={containerRef} className="max-h-[calc(100vh-6rem)] space-y-10 overflow-y-auto pr-4" data-testid="desktop-wizard-sections">
    <section id="step-1" tabIndex={-1}><h1 className="text-h1">Niños</h1><div className="mt-4 space-y-5"><p>¿Cuántos niños cuidarás?</p><div className="flex items-center gap-5"><button type="button" aria-label="Quitar niño" className="min-h-11 min-w-11 rounded-sm border border-border-strong text-xl" onClick={() => update({ children: data.children.slice(0, -1) })}>−</button><span>{data.children.length}</span><button type="button" aria-label="Agregar niño" className="min-h-11 min-w-11 rounded-sm border border-border-strong text-xl" onClick={() => update({ children: [...data.children, ""] as WizardData["children"] })}>+</button></div>{data.children.map((age, i) => <fieldset key={i}><legend className="mb-2 text-body-sm">Edad del niño {i + 1}</legend><div className="flex flex-wrap gap-2">{rangoEdadValues.map((value) => <button key={value} type="button" aria-pressed={age === value} className={`min-h-11 rounded-full border px-4 py-2 text-body-sm ${age === value ? "border-primary-600 bg-primary-50" : "border-border-strong"}`} onClick={() => update({ children: data.children.map((item, index) => index === i ? value : item) as WizardData["children"] })}>{value}</button>)}</div></fieldset>)}</div></section>
     <section id="step-2" tabIndex={-1}><h2 className="text-h2">Zona</h2><div className="mt-3"><ZonaAutocomplete zonas={zonas} name="zona_id" defaultZonaId={data.zonaId} onSelect={(zona) => update({ zonaId: zona.id })} /></div></section>
    <section id="step-3" tabIndex={-1}><h2 className="text-h2">Días y horarios</h2><div className="mt-3 space-y-3">{["lun", "mar", "mie", "jue", "vie", "sab", "dom"].map((day) => { const current = data.diasHorarios.find((item) => item.dia === day); return <div key={day} className="flex items-center gap-3"><button type="button" aria-pressed={!!current} onClick={() => update({ diasHorarios: current ? data.diasHorarios.filter((item) => item.dia !== day) : [...data.diasHorarios, { dia: day as "lun", horaInicio: "09:00", horaFin: "17:00" }] })} className="min-h-11 min-w-16 rounded-full border border-border-strong px-3">{day}</button>{current && <><input aria-label={`${day} desde`} type="time" className="h-11 rounded-sm border border-border-strong bg-bg-raised px-2" value={current.horaInicio} onChange={(event) => update({ diasHorarios: data.diasHorarios.map((item) => item.dia === day ? { ...item, horaInicio: event.target.value } : item) })} /><input aria-label={`${day} hasta`} type="time" className="h-11 rounded-sm border border-border-strong bg-bg-raised px-2" value={current.horaFin} onChange={(event) => update({ diasHorarios: data.diasHorarios.map((item) => item.dia === day ? { ...item, horaFin: event.target.value } : item) })} /></>}</div>; })}</div></section>
     <section id="step-4" tabIndex={-1}><h2 className="text-h2">Modalidad</h2><div className="mt-3 flex flex-wrap gap-2">{[["planta", "Planta"], ["entrada_salida", "Entrada por salida"], ["ocasional", "Ocasional"]].map(([value, label]) => <button key={value} type="button" aria-pressed={data.modalidad === value} onClick={() => update({ modalidad: value as WizardData["modalidad"] })} className="min-h-11 rounded-sm border border-border-strong px-4">{label}</button>)}</div></section>
     <section id="step-5" tabIndex={-1}><h2 className="text-h2">Rango de pago</h2><div className="mt-3 flex gap-3"><label className="flex min-w-0 flex-1 items-center rounded-sm border border-border-strong bg-bg-raised"><span className="px-3 text-ink-600">MXN</span><input aria-label="Pago mínimo en MXN" type="number" min="0" className="h-11 min-w-0 flex-1 bg-transparent px-2 outline-none" value={data.pagoMin ?? ""} onChange={(event) => update({ pagoMin: event.target.value ? Number(event.target.value) : undefined })} /></label><label className="flex min-w-0 flex-1 items-center rounded-sm border border-border-strong bg-bg-raised"><span className="px-3 text-ink-600">MXN</span><input aria-label="Pago máximo en MXN" type="number" min="0" className="h-11 min-w-0 flex-1 bg-transparent px-2 outline-none" value={data.pagoMax ?? ""} onChange={(event) => update({ pagoMax: event.target.value ? Number(event.target.value) : undefined })} /></label></div><p className="mt-2 text-body-sm text-ink-600">{paymentSummary}</p></section>
     <section id="step-6" tabIndex={-1}><h2 className="text-h2">Fecha de inicio</h2><input aria-label="Fecha de inicio" type="date" min={new Date().toISOString().slice(0, 10)} className="mt-3 h-11 rounded-sm border border-border-strong bg-bg-raised px-3" value={data.fechaInicio ?? ""} onChange={(event) => update({ fechaInicio: event.target.value })} /></section>
     <section id="step-7" tabIndex={-1}><h2 className="text-h2">Responsabilidades</h2><div className="mt-3 space-y-3">{responsibilityOptions.map((item) => <label key={item} className="flex min-h-11 items-center gap-3 text-body"><input type="checkbox" checked={data.responsabilidades.includes(item)} onChange={(event) => update({ responsabilidades: event.target.checked ? [...data.responsabilidades, item] : data.responsabilidades.filter((x) => x !== item) })} />{item}</label>)}<label className="flex flex-col gap-2 text-body-sm">Otros<textarea aria-label="Otros" value={data.responsabilidades.find((item) => !responsibilityOptions.includes(item)) ?? ""} className="rounded-sm border border-border-strong bg-bg-raised p-3" onChange={(event) => update({ responsabilidades: event.target.value ? [...data.responsabilidades.filter((x) => responsibilityOptions.includes(x)), event.target.value] : data.responsabilidades.filter((x) => responsibilityOptions.includes(x)) })} /></label></div></section>
    <p className="border-t border-border pt-5 text-body-sm text-ink-600">La revisión y publicación de la necesidad corresponden a E2-02.</p>
  </div>;
}

function DesktopActions({ canNext, error, isPending, step, back, next, exit }: { canNext: boolean; error: string; isPending: boolean; step: number; back: () => void; next: () => void; exit: () => void }) {
  return <div className="mt-8 flex flex-wrap gap-3 border-t border-border pt-4"><button type="button" disabled={isPending || step === 1} onClick={back} className="min-h-11 rounded-sm px-4 py-3 text-button text-ink-600 disabled:opacity-40">Atrás</button><button type="button" disabled={isPending} onClick={exit} className="min-h-11 rounded-sm px-4 py-3 text-button text-ink-600 disabled:opacity-40">Guardar y salir</button><button type="button" disabled={!canNext || isPending} onClick={next} className="flex min-h-11 flex-1 items-center justify-center rounded-sm bg-primary-600 px-4 py-3 text-button text-white disabled:opacity-40">{isPending ? <SpinnerGap size={16} className="animate-spin" aria-label="Guardando" /> : step === 7 ? "Guardar borrador" : "Siguiente"}</button>{error && <p role="alert" className="basis-full text-body-sm text-danger-600">{error}</p>}</div>;
}
