#!/usr/bin/env python3
"""Render shared roles into native harness files using only the Python standard library."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
HARNESSES = ("claude", "opencode", "codex")
MANIFEST = "adapters/generated-checksums.json"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def instructions(root, role):
    source = root / role["source"]
    text = source.read_text()
    if role.get("legacy"):
        # Product roles are explicitly outside this migration. Read, never rewrite them.
        return text.split("---", 2)[2].strip()
    parts = re.split(r"^## Mode: ([a-z-]+)\s*$", text, flags=re.MULTILINE)
    modes = dict(zip(parts[1::2], parts[2::2]))
    if len(modes) != len(parts[1::2]) or role["mode"] not in modes:
        raise ValueError("Missing or duplicate mode in " + role["source"])
    return (parts[0].strip() + "\n\n## Mode: " + role["mode"] + "\n"
            + modes[role["mode"]].rstrip())


def render(root, harnesses):
    registry = json.loads((root / "adapters/roles.json").read_text())
    output = {}
    for harness in harnesses:
        extension = "toml" if harness == "codex" else "md"
        for name, role in registry.items():
            if role.get("legacy") and harness != "codex":
                continue
            template = root / "adapters" / harness / "templates" / (name + "." + extension)
            content = template.read_text()
            if content.count("{{instructions}}") != 1:
                raise ValueError("Expected one instructions placeholder: " + str(template))
            body = instructions(root, role)
            body = ("Read AGENTS.md at the venture root before executing the assigned task. "
                    "Use the venture directory as the working directory for artifact paths.\n\n" + body)
            if harness == "codex":
                content = "# Generated by scripts/render-adapters.py; edit agents/ and adapters/.\n" + content
                body = json.dumps(body, ensure_ascii=False)
            else:
                body = "<!-- Generated by scripts/render-adapters.py; edit agents/ and adapters/. -->\n\n" + body
            path = "." + harness + "/agents/" + name + "." + extension
            output[path] = content.replace("{{instructions}}", body).encode()
        if harness == "claude":
            output["CLAUDE.md"] = (root / "adapters/claude/CLAUDE.md").read_bytes()
    return output


def read_manifest(path):
    return json.loads(path.read_text()) if path.exists() else {}


def install(root, target, harnesses, check=False, preflight=False):
    output = render(root, harnesses)
    manifest = target / MANIFEST
    if manifest.is_symlink() or not manifest.resolve().is_relative_to(target.resolve()):
        raise ValueError("Refusing unsafe checksum manifest: " + MANIFEST)
    previous = read_manifest(manifest)
    legacy = read_manifest(root / "adapters/legacy-checksums.json")
    problems = []
    for relative, data in output.items():
        path = target / relative
        if path.is_symlink():
            problems.append("Refusing symlink output: " + relative)
        elif not path.resolve().is_relative_to(target.resolve()):
            problems.append("Output escapes target: " + relative)
        elif check:
            if not path.exists() or path.read_bytes() != data:
                problems.append("Out of date: " + relative)
        elif path.exists() and path.read_bytes() != data:
            current = digest(path.read_bytes())
            if current not in (previous.get(relative), legacy.get(relative)):
                problems.append("Locally modified or unmanaged output: " + relative)
    if problems:
        raise ValueError("\n".join(problems))
    if check or preflight:
        return len(output)
    # Check every destination before writing any output. Do not replace runtime settings.
    for relative, data in output.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_bytes() != data:
            path.write_bytes(data)
        previous[relative] = digest(data)
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(json.dumps(previous, indent=2, sort_keys=True) + "\n")
    return len(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--harness", choices=("all",) + HARNESSES, default="all")
    parser.add_argument("--target", type=Path, default=ROOT,
                        help="Venture directory to receive native files (default: this repository)")
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--check", action="store_true", help="Check generated files without writing")
    modes.add_argument("--preflight", action="store_true", help="Check installation conflicts without writing")
    args = parser.parse_args()
    harnesses = HARNESSES if args.harness == "all" else (args.harness,)
    try:
        count = install(ROOT, args.target.resolve(), harnesses, args.check, args.preflight)
    except (ValueError, OSError, KeyError) as error:
        print(str(error), file=sys.stderr)
        return 1
    verb = "Checked" if args.check else ("Preflighted" if args.preflight else "Rendered")
    print(verb + " {} native files.".format(count))
    return 0


if __name__ == "__main__":
    sys.exit(main())
